name: Publish Workflow / Complete
description: It finish publishing

inputs:
  branch:
    description: target branch for git push
    required: true
  prev_version:
    description: package's prev version
    required: true
  next_version:
    description: package's next version
    required: true
  npm_tag:
    description: tag for NPM artifact
    required: false
  token:
    description: token for write access to repository
    required: true

runs:
  using: composite
  steps:
    - name: Publishing release
      if: ${{ !inputs.npm_tag }}
      run: npm publish --access public
      shell: bash

    - name: Publishing release with npm_tag
      if: ${{ inputs.npm_tag }}
      run: npm publish --access public --tag ${{ inputs.npm_tag }}
      shell: bash

    - name: Commit version changes
      run: |
        git add package.json
        git commit -m "bump(vk-mini-apps-router): from ${{ inputs.prev_version }} to ${{ inputs.next_version }}"
      shell: bash

    - name: Create tag
      run: git tag vk-mini-apps-router@${{ inputs.next_version }}
      shell: bash

    - name: Pushing changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        tags: true
